services:
  - type: web
    name: youtube-monitoring-app
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/frontend/streamlit_app.py --server.port=10000 --server.headless=true --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 10000